

export const LIGHT_LIST_REQUEST = 'LIGHT_LIST_REQUEST';
export const LIGHT_LIST_SUCCESS = 'LIGHT_LIST_SUCCESS';
export const LIGHT_LIST_FAIL = 'LIGHT_LIST_FAIL';
export const LIGHT_FAVORITE_REQUEST = 'USER_FAVORITE_REQUEST';
export const LIGHT_ADD_FAVORITE_SUCCESS = 'USER_ADD_FAVORITE_SUCCESS';
export const LIGHT_REM_FAVORITE_SUCCESS = 'USER_REM_FAVORITE_SUCCESS';
export const FAVORITE_LIST_REQUEST = 'USER_LIST_REQUEST';
export const FAVORITE_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const LIGHT_LIST_DELETE = 'LIGHT_LIST_DELETE';
export const EDIT_WARNING_LIGHT = 'DELETE_WARNING_LIGHT';
export const LIGHT_LIST_ADD = 'LIGHT_LIST_ADD';
